import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [version, setVersion] = useState("");
  useEffect(() => {
    const getApi = async () => {
      fetch("http://clients.frenteloja.local/api/version")
        .then((data) => data.json())
        .then((response) => setVersion(response.versao));
    };

    getApi();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next TR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Versão {version && version}</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
