import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [version, setVersion] = useState("");
  useEffect(() => {
    const getApi = async () => {
      fetch("http://clients.frenteloja.local/api/version")
        .then((data) => data.json())
        .then((response) => setVersion(response.versao));
    };

    getApi();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Versão {version && version}</h1>
      </main>
    </div>
  );
};

export default Home;
