version: '3'

services:
  nginx:
    build:
      context: "./nginx"
    depends_on:
      - clients-web
      - app  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf:/etc/nginx/conf.d"
      - "./www:/var/www"
      - "./nginx/conf/logs:/var/log/nginx"
      - "./nginx/conf/ssl:/ssl"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - clients-web 
      - app
    networks:
     - app-network
  clients-web:
    build:
      context: "./web"
    container_name: clients-web
    ports:
      - "9000:9000"
    volumes:
      - "./www:/var/www"
    networks:
      - app-network
  app:
    build:
      context: "./front"
    container_name: app
    ports:
      - 8001:3000
    stdin_open: true
    volumes:
      - "./front:/usr/src/app"
    networks:
      - app-network
    restart: unless-stopped
    
networks: 
  app-network:
    driver: bridge
    