version: '3'

services:
  nginx:
    build:
      context: "./nginx"
    depends_on:
      - web  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf:/etc/nginx/conf.d"
      - "./www:/var/www"
      - "./nginx/conf/logs:/var/log/nginx"
      - "./nginx/conf/ssl:/ssl"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - web 
    networks:
     - app-network
  web:
    build:
      context: "./web"
    ports:
      - "9000:9000"
    volumes:
      - "./www:/var/www"
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge
    